# Generated by Django 5.1.3 on 2024-11-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_list", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="is_done",
            field=models.BooleanField(default=False),
        ),
    ]
