# Generated by Django 5.1.3 on 2024-11-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_list", "0002_todo_is_done"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="is_done",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
