# Generated by Django 5.1.3 on 2024-11-27 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_list", "0003_alter_todo_is_done"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="deadline",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 27, 10, 22, 27, 520009)
            ),
        ),
    ]
