# Generated by Django 5.1.3 on 2024-11-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_list", "0004_todo_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="deadline",
            field=models.DateTimeField(),
        ),
    ]
