# Generated by Django 5.1.3 on 2024-11-27 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo_list", "0005_alter_todo_deadline"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ToDo",
            new_name="Task",
        ),
    ]
