# Generated by Django 5.1.3 on 2024-11-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_list", "0006_rename_todo_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(null=True),
        ),
    ]
